
project:
  name: "test"
  data_directory: "/home/pmuehleder/data/game_metadata/sources"
  export_directory: "/home/pmuehleder/data/game_metadata/daft_export"

datasets:
  mobygames:
    api_key: "***REMOVED***"
  giantbomb:
    api_key: "***REMOVED***"

export:
  mobygames:
      - title
      - alt_titles
      - platforms
  mediaartdb:
      - title
      - alt_titles
      - platforms